import type { CityEntry } from './types'

export const CITY_ENTRIES: CityEntry[] = [
  { iata: 'ABZ', en: 'Aberdeen', ru: 'Абердин' },
  { iata: 'ADB', en: 'Izmir', ru: 'Измир' },
  { iata: 'ADD', en: 'Addis Ababa', ru: 'Аддис-Абеба' },
  { iata: 'AKL', en: 'Auckland', ru: 'Окленд' },
  { iata: 'ALA', en: 'Almaty', ru: 'Алматы' },
  { iata: 'ALG', en: 'Algiers', ru: 'Алжир' },
  { iata: 'AMM', en: 'Amman', ru: 'Амман' },
  { iata: 'AMS', en: 'Amsterdam', ru: 'Амстердам' },
  { iata: 'ANC', en: 'Anchorage', ru: 'Анкоридж' },
  { iata: 'ARN', en: 'Stockholm', ru: 'Стокгольм' },
  { iata: 'ASB', en: 'Ashgabat', ru: 'Ашхабад' },
  { iata: 'ATH', en: 'Athens', ru: 'Афины' },
  { iata: 'ATL', en: 'Atlanta', ru: 'Атланта' },
  { iata: 'AUH', en: 'Abu Dhabi', ru: 'Абу-Даби' },
  { iata: 'AYT', en: 'Antalya', ru: 'Анталья' },
  { iata: 'BAH', en: 'Bahrain', ru: 'Бахрейн' },
  { iata: 'BAK', en: 'Baku', ru: 'Баку', aliasesEn: ['Baku Heydar Aliyev'], aliasesRu: ['Баку Гейдар Алиев'] },
  { iata: 'BCN', en: 'Barcelona', ru: 'Барселона' },
  { iata: 'BEG', en: 'Belgrade', ru: 'Белград' },
  { iata: 'BER', en: 'Berlin', ru: 'Берлин' },
  { iata: 'BGW', en: 'Baghdad', ru: 'Багдад' },
  { iata: 'BHX', en: 'Birmingham', ru: 'Бирмингем' },
  { iata: 'BJS', en: 'Beijing', ru: 'Пекин' },
  { iata: 'BKK', en: 'Bangkok', ru: 'Бангкок' },
  { iata: 'BLQ', en: 'Bologna', ru: 'Болонья' },
  { iata: 'BNE', en: 'Brisbane', ru: 'Брисбен' },
  { iata: 'BOG', en: 'Bogota', ru: 'Богота' },
  { iata: 'BOM', en: 'Mumbai', ru: 'Мумбаи' },
  { iata: 'BOS', en: 'Boston', ru: 'Бостон' },
  { iata: 'BRU', en: 'Brussels', ru: 'Брюссель' },
  { iata: 'BSB', en: 'Brasilia', ru: 'Бразилиа' },
  { iata: 'BUD', en: 'Budapest', ru: 'Будапешт' },
  { iata: 'CAI', en: 'Cairo', ru: 'Каир' },
  { iata: 'CAN', en: 'Guangzhou', ru: 'Гуанчжоу' },
  { iata: 'CCS', en: 'Caracas', ru: 'Каракас' },
  { iata: 'CDG', en: 'Paris', ru: 'Париж', aliasesEn: ['Paris Charles de Gaulle'], aliasesRu: ['Париж Шарль-де-Голль'] },
  { iata: 'CGK', en: 'Jakarta', ru: 'Джакарта' },
  { iata: 'CMN', en: 'Casablanca', ru: 'Касабланка' },
  { iata: 'CMB', en: 'Colombo', ru: 'Коломбо' },
  { iata: 'CPH', en: 'Copenhagen', ru: 'Копенгаген' },
  { iata: 'CPT', en: 'Cape Town', ru: 'Кейптаун' },
  { iata: 'CTS', en: 'Sapporo', ru: 'Саппоро' },
  { iata: 'DAC', en: 'Dhaka', ru: 'Дакка' },
  { iata: 'DAR', en: 'Dar es Salaam', ru: 'Дар-эс-Салам' },
  { iata: 'DEL', en: 'Delhi', ru: 'Дели' },
  { iata: 'DEN', en: 'Denver', ru: 'Денвер' },
  { iata: 'DME', en: 'Moscow', ru: 'Москва', aliasesEn: ['Moscow Domodedovo'], aliasesRu: ['Москва Домодедово'] },
  { iata: 'DOH', en: 'Doha', ru: 'Доха' },
  { iata: 'DPS', en: 'Bali', ru: 'Бали', aliasesEn: ['Denpasar'], aliasesRu: ['Денпасар'] },
  { iata: 'DTW', en: 'Detroit', ru: 'Детройт' },
  { iata: 'DUB', en: 'Dublin', ru: 'Дублин' },
  { iata: 'DUS', en: 'Dusseldorf', ru: 'Дюссельдорф' },
  { iata: 'DXB', en: 'Dubai', ru: 'Дубай' },
  { iata: 'EDI', en: 'Edinburgh', ru: 'Эдинбург' },
  { iata: 'EVN', en: 'Yerevan', ru: 'Ереван' },
  { iata: 'EZE', en: 'Buenos Aires', ru: 'Буэнос-Айрес' },
  { iata: 'FCO', en: 'Rome', ru: 'Рим', aliasesEn: ['Rome Fiumicino'], aliasesRu: ['Рим Фьюмичино'] },
  { iata: 'FRA', en: 'Frankfurt', ru: 'Франкфурт' },
  { iata: 'GDN', en: 'Gdansk', ru: 'Гданьск' },
  { iata: 'GIG', en: 'Rio de Janeiro', ru: 'Рио-де-Жанейро' },
  { iata: 'GLA', en: 'Glasgow', ru: 'Глазго' },
  { iata: 'GRU', en: 'Sao Paulo', ru: 'Сан-Паулу' },
  { iata: 'GVA', en: 'Geneva', ru: 'Женева' },
  { iata: 'GYD', en: 'Baku', ru: 'Баку' },
  { iata: 'HAJ', en: 'Hanover', ru: 'Ганновер' },
  { iata: 'HAM', en: 'Hamburg', ru: 'Гамбург' },
  { iata: 'HAN', en: 'Hanoi', ru: 'Ханой' },
  { iata: 'HEL', en: 'Helsinki', ru: 'Хельсинки' },
  { iata: 'HKG', en: 'Hong Kong', ru: 'Гонконг' },
  { iata: 'HND', en: 'Tokyo Haneda', ru: 'Токио Ханэда', aliasesEn: ['Haneda'], aliasesRu: ['Ханэда'] },
  { iata: 'HNL', en: 'Honolulu', ru: 'Гонолулу' },
  { iata: 'HKT', en: 'Phuket', ru: 'Пхукет' },
  { iata: 'IAH', en: 'Houston', ru: 'Хьюстон' },
  { iata: 'ICN', en: 'Seoul', ru: 'Сеул' },
  { iata: 'IAD', en: 'Washington', ru: 'Вашингтон' },
  { iata: 'IKA', en: 'Tehran', ru: 'Тегеран' },
  { iata: 'IND', en: 'Indianapolis', ru: 'Индианаполис' },
  { iata: 'IST', en: 'Istanbul', ru: 'Стамбул', aliasesEn: ['Istanbul Airport'], aliasesRu: ['Стамбул Аэропорт'] },
  { iata: 'JED', en: 'Jeddah', ru: 'Джидда' },
  { iata: 'JFK', en: 'New York', ru: 'Нью-Йорк', aliasesEn: ['New York JFK'], aliasesRu: ['Нью-Йорк Джон Кеннеди'] },
  { iata: 'JNB', en: 'Johannesburg', ru: 'Йоханнесбург' },
  { iata: 'KBP', en: 'Kyiv', ru: 'Киев' },
  { iata: 'KHI', en: 'Karachi', ru: 'Карачи' },
  { iata: 'KIX', en: 'Osaka', ru: 'Осака' },
  { iata: 'KIV', en: 'Chisinau', ru: 'Кишинев' },
  { iata: 'KRR', en: 'Krasnodar', ru: 'Краснодар' },
  { iata: 'KUL', en: 'Kuala Lumpur', ru: 'Куала-Лумпур' },
  { iata: 'KWI', en: 'Kuwait City', ru: 'Кувейт' },
  { iata: 'KZN', en: 'Kazan', ru: 'Казань' },
  { iata: 'LAS', en: 'Las Vegas', ru: 'Лас-Вегас' },
  { iata: 'LAX', en: 'Los Angeles', ru: 'Лос-Анджелес' },
  { iata: 'LED', en: 'Saint Petersburg', ru: 'Санкт-Петербург', aliasesEn: ['St Petersburg', 'Saint-Petersburg'], aliasesRu: ['Петербург', 'Санкт Петербург'] },
  { iata: 'LGA', en: 'New York LaGuardia', ru: 'Нью-Йорк Ла-Гуардия' },
  { iata: 'LGW', en: 'London', ru: 'Лондон', aliasesEn: ['London Gatwick'], aliasesRu: ['Лондон Гатвик'] },
  { iata: 'LHR', en: 'London', ru: 'Лондон', aliasesEn: ['London Heathrow'], aliasesRu: ['Лондон Хитроу'] },
  { iata: 'LIM', en: 'Lima', ru: 'Лима' },
  { iata: 'LIS', en: 'Lisbon', ru: 'Лиссабон' },
  { iata: 'LON', en: 'London', ru: 'Лондон' },
  { iata: 'LPA', en: 'Las Palmas', ru: 'Лас-Пальмас' },
  { iata: 'LYS', en: 'Lyon', ru: 'Лион' },
  { iata: 'MAD', en: 'Madrid', ru: 'Мадрид' },
  { iata: 'MAN', en: 'Manchester', ru: 'Манчестер' },
  { iata: 'MCT', en: 'Muscat', ru: 'Маскат' },
  { iata: 'MEL', en: 'Melbourne', ru: 'Мельбурн' },
  { iata: 'MEX', en: 'Mexico City', ru: 'Мехико' },
  { iata: 'MIA', en: 'Miami', ru: 'Майами' },
  { iata: 'MLE', en: 'Male', ru: 'Мале' },
  { iata: 'MRU', en: 'Mauritius', ru: 'Маврикий' },
  { iata: 'MLA', en: 'Malta', ru: 'Мальта' },
  { iata: 'MNL', en: 'Manila', ru: 'Манила' },
  { iata: 'MOW', en: 'Moscow', ru: 'Москва' },
  { iata: 'MSP', en: 'Minneapolis', ru: 'Миннеаполис' },
  { iata: 'MUC', en: 'Munich', ru: 'Мюнхен' },
  { iata: 'NBO', en: 'Nairobi', ru: 'Найроби' },
  { iata: 'NCE', en: 'Nice', ru: 'Ницца' },
  { iata: 'NGO', en: 'Nagoya', ru: 'Нагоя' },
  { iata: 'NQZ', en: 'Astana', ru: 'Астана' },
  { iata: 'NRT', en: 'Tokyo', ru: 'Токио', aliasesEn: ['Tokyo Narita'], aliasesRu: ['Токио Нарита'] },
  { iata: 'NYC', en: 'New York', ru: 'Нью-Йорк' },
  { iata: 'NUE', en: 'Nuremberg', ru: 'Нюрнберг' },
  { iata: 'OPO', en: 'Porto', ru: 'Порту' },
  { iata: 'ORD', en: 'Chicago', ru: 'Чикаго' },
  { iata: 'OSL', en: 'Oslo', ru: 'Осло' },
  { iata: 'OTP', en: 'Bucharest', ru: 'Бухарест' },
  { iata: 'PDL', en: 'Ponta Delgada', ru: 'Понта-Делгада' },
  { iata: 'PEK', en: 'Beijing', ru: 'Пекин' },
  { iata: 'PER', en: 'Perth', ru: 'Перт' },
  { iata: 'PHL', en: 'Philadelphia', ru: 'Филадельфия' },
  { iata: 'PHX', en: 'Phoenix', ru: 'Финикс' },
  { iata: 'PMI', en: 'Palma de Mallorca', ru: 'Пальма-де-Майорка' },
  { iata: 'PRG', en: 'Prague', ru: 'Прага' },
  { iata: 'PTY', en: 'Panama City', ru: 'Панама' },
  { iata: 'PVG', en: 'Shanghai', ru: 'Шанхай' },
  { iata: 'RIX', en: 'Riga', ru: 'Рига' },
  { iata: 'RKT', en: 'Ras Al Khaimah', ru: 'Рас-эль-Хайма' },
  { iata: 'ROM', en: 'Rome', ru: 'Рим' },
  { iata: 'RUH', en: 'Riyadh', ru: 'Эр-Рияд' },
  { iata: 'SAW', en: 'Istanbul Sabiha', ru: 'Стамбул Сабиха', aliasesEn: ['Sabiha Gokcen'], aliasesRu: ['Сабиха Гёкчен'] },
  { iata: 'SEA', en: 'Seattle', ru: 'Сиэтл' },
  { iata: 'SFO', en: 'San Francisco', ru: 'Сан-Франциско' },
  { iata: 'SHA', en: 'Shanghai Hongqiao', ru: 'Шанхай Хунцяо' },
  { iata: 'SIN', en: 'Singapore', ru: 'Сингапур' },
  { iata: 'SKG', en: 'Thessaloniki', ru: 'Салоники' },
  { iata: 'SOF', en: 'Sofia', ru: 'София' },
  { iata: 'SPU', en: 'Split', ru: 'Сплит' },
  { iata: 'SVO', en: 'Moscow Sheremetyevo', ru: 'Москва Шереметьево', aliasesEn: ['Sheremetyevo'], aliasesRu: ['Шереметьево'] },
  { iata: 'SYD', en: 'Sydney', ru: 'Сидней' },
  { iata: 'TAS', en: 'Tashkent', ru: 'Ташкент' },
  { iata: 'TBS', en: 'Tbilisi', ru: 'Тбилиси' },
  { iata: 'TFN', en: 'Tenerife', ru: 'Тенерифе' },
  { iata: 'TFS', en: 'Tenerife South', ru: 'Тенерифе Южный' },
  { iata: 'TLV', en: 'Tel Aviv', ru: 'Тель-Авив' },
  { iata: 'TRN', en: 'Turin', ru: 'Турин' },
  { iata: 'TUN', en: 'Tunis', ru: 'Тунис' },
  { iata: 'UFA', en: 'Ufa', ru: 'Уфа' },
  { iata: 'VCE', en: 'Venice', ru: 'Венеция' },
  { iata: 'VIE', en: 'Vienna', ru: 'Вена' },
  { iata: 'VKO', en: 'Moscow Vnukovo', ru: 'Москва Внуково', aliasesEn: ['Vnukovo'], aliasesRu: ['Внуково'] },
  { iata: 'VNO', en: 'Vilnius', ru: 'Вильнюс' },
  { iata: 'WAW', en: 'Warsaw', ru: 'Варшава' },
  { iata: 'WRO', en: 'Wroclaw', ru: 'Вроцлав' },
  { iata: 'YEG', en: 'Edmonton', ru: 'Эдмонтон' },
  { iata: 'YUL', en: 'Montreal', ru: 'Монреаль' },
  { iata: 'YYC', en: 'Calgary', ru: 'Калгари' },
  { iata: 'YYZ', en: 'Toronto', ru: 'Торонто' },
  { iata: 'ZAG', en: 'Zagreb', ru: 'Загреб' },
  { iata: 'ZRH', en: 'Zurich', ru: 'Цюрих' },

  // Russian domestic
  { iata: 'OVB', en: 'Novosibirsk', ru: 'Новосибирск' },
  { iata: 'SVX', en: 'Yekaterinburg', ru: 'Екатеринбург' },
  { iata: 'IKT', en: 'Irkutsk', ru: 'Иркутск' },
  { iata: 'OMS', en: 'Omsk', ru: 'Омск' },
  { iata: 'VOG', en: 'Volgograd', ru: 'Волгоград' },
  { iata: 'ROV', en: 'Rostov-on-Don', ru: 'Ростов-на-Дону', aliasesRu: ['Ростов'] },
  { iata: 'PEE', en: 'Perm', ru: 'Пермь' },
  { iata: 'CEK', en: 'Chelyabinsk', ru: 'Челябинск' },
  { iata: 'GOJ', en: 'Nizhny Novgorod', ru: 'Нижний Новгород', aliasesRu: ['Нижний'] },
  { iata: 'KHV', en: 'Khabarovsk', ru: 'Хабаровск' },
  { iata: 'VVO', en: 'Vladivostok', ru: 'Владивосток' },
  { iata: 'TJM', en: 'Tyumen', ru: 'Тюмень' },
  { iata: 'UUS', en: 'Yuzhno-Sakhalinsk', ru: 'Южно-Сахалинск' },
  { iata: 'PKC', en: 'Petropavlovsk-Kamchatsky', ru: 'Петропавловск-Камчатский', aliasesRu: ['Петропавловск'] },
  { iata: 'MMK', en: 'Murmansk', ru: 'Мурманск' },
  { iata: 'ARH', en: 'Arkhangelsk', ru: 'Архангельск' },
  { iata: 'HTA', en: 'Chita', ru: 'Чита' },
  { iata: 'YKS', en: 'Yakutsk', ru: 'Якутск' },
  { iata: 'SGC', en: 'Surgut', ru: 'Сургут' },
  { iata: 'VOZ', en: 'Voronezh', ru: 'Воронеж' },
  { iata: 'STW', en: 'Stavropol', ru: 'Ставрополь' },
  { iata: 'MRV', en: 'Mineralnye Vody', ru: 'Минеральные Воды', aliasesRu: ['Мин Воды'] },
  { iata: 'ASF', en: 'Astrakhan', ru: 'Астрахань' },
  { iata: 'SKX', en: 'Saransk', ru: 'Саранск' },
  { iata: 'IAR', en: 'Yaroslavl', ru: 'Ярославль' },
  { iata: 'TBW', en: 'Tambov', ru: 'Тамбов' },

  // Egypt / Middle East resort
  { iata: 'SSH', en: 'Sharm el-Sheikh', ru: 'Шарм-эль-Шейх', aliasesRu: ['Шарм'] },
  { iata: 'HRG', en: 'Hurghada', ru: 'Хургада' },
  { iata: 'LXR', en: 'Luxor', ru: 'Луксор' },
  { iata: 'ASW', en: 'Aswan', ru: 'Асуан' },

  // Southeast Asia
  { iata: 'SGN', en: 'Ho Chi Minh City', ru: 'Хошимин', aliasesEn: ['Saigon'], aliasesRu: ['Сайгон'] },
  { iata: 'DAD', en: 'Da Nang', ru: 'Дананг' },
  { iata: 'CXR', en: 'Nha Trang', ru: 'Нячанг' },
  { iata: 'KBV', en: 'Krabi', ru: 'Краби' },
  { iata: 'USM', en: 'Koh Samui', ru: 'Самуи', aliasesEn: ['Samui'], aliasesRu: ['Ко Самуи'] },
  { iata: 'CNX', en: 'Chiang Mai', ru: 'Чиангмай' },
  { iata: 'UTP', en: 'Pattaya', ru: 'Паттайя', aliasesEn: ['U-Tapao'], aliasesRu: ['Утапао'] },
  { iata: 'REP', en: 'Siem Reap', ru: 'Сием Рип' },
  { iata: 'PNH', en: 'Phnom Penh', ru: 'Пномпень' },
  { iata: 'RGN', en: 'Yangon', ru: 'Янгон' },
  { iata: 'VTE', en: 'Vientiane', ru: 'Вьентьян' },

  // South Asia
  { iata: 'BLR', en: 'Bangalore', ru: 'Бангалор' },
  { iata: 'MAA', en: 'Chennai', ru: 'Ченнаи' },
  { iata: 'CCU', en: 'Kolkata', ru: 'Калькутта' },
  { iata: 'HYD', en: 'Hyderabad', ru: 'Хайдарабад' },
  { iata: 'AMD', en: 'Ahmedabad', ru: 'Ахмедабад' },
  { iata: 'GOI', en: 'Goa', ru: 'Гоа' },

  // Caribbean / Latin America
  { iata: 'PUJ', en: 'Punta Cana', ru: 'Пунта-Кана' },
  { iata: 'CUN', en: 'Cancun', ru: 'Канкун' },
  { iata: 'HAV', en: 'Havana', ru: 'Гавана' },
  { iata: 'SDQ', en: 'Santo Domingo', ru: 'Санто-Доминго' },
  { iata: 'MBJ', en: 'Montego Bay', ru: 'Монтего-Бей' },
  { iata: 'SCL', en: 'Santiago', ru: 'Сантьяго' },
  { iata: 'UIO', en: 'Quito', ru: 'Кито' },
  { iata: 'GYE', en: 'Guayaquil', ru: 'Гуаякиль' },
  { iata: 'MVD', en: 'Montevideo', ru: 'Монтевидео' },
  { iata: 'ASU', en: 'Asuncion', ru: 'Асунсьон' },

  // Africa
  { iata: 'ZNZ', en: 'Zanzibar', ru: 'Занзибар' },
  { iata: 'MBA', en: 'Mombasa', ru: 'Момбаса' },
  { iata: 'SEZ', en: 'Mahe', ru: 'Сейшелы', aliasesEn: ['Seychelles'], aliasesRu: ['Маэ'] },
  { iata: 'LOS', en: 'Lagos', ru: 'Лагос' },
  { iata: 'ACC', en: 'Accra', ru: 'Аккра' },
  { iata: 'DKR', en: 'Dakar', ru: 'Дакар' },
  { iata: 'LUN', en: 'Lusaka', ru: 'Лусака' },
  { iata: 'HRE', en: 'Harare', ru: 'Харэре' },
  { iata: 'TNR', en: 'Antananarivo', ru: 'Антананариву' },
  { iata: 'RUN', en: 'Reunion', ru: 'Реюньон' },

  // Europe extras
  { iata: 'NAP', en: 'Naples', ru: 'Неаполь' },
  { iata: 'MRS', en: 'Marseille', ru: 'Марсель' },
  { iata: 'AGP', en: 'Malaga', ru: 'Малага' },
  { iata: 'SVQ', en: 'Seville', ru: 'Севилья' },
  { iata: 'MXP', en: 'Milan Malpensa', ru: 'Милан Мальпенса', aliasesEn: ['Milan'], aliasesRu: ['Милан'] },
  { iata: 'BGY', en: 'Milan Bergamo', ru: 'Милан Бергамо', aliasesEn: ['Bergamo'], aliasesRu: ['Бергамо'] },
  { iata: 'PSA', en: 'Pisa', ru: 'Пиза' },
  { iata: 'CTA', en: 'Catania', ru: 'Катания' },
  { iata: 'PMO', en: 'Palermo', ru: 'Палермо' },
  { iata: 'BRI', en: 'Bari', ru: 'Бари' },
  { iata: 'BTS', en: 'Bratislava', ru: 'Братислава' },
  { iata: 'KTW', en: 'Katowice', ru: 'Катовице' },
  { iata: 'POZ', en: 'Poznan', ru: 'Познань' },
  { iata: 'TLL', en: 'Tallinn', ru: 'Таллин' },
  { iata: 'KUN', en: 'Kaunas', ru: 'Каунас' },
  { iata: 'TMP', en: 'Tampere', ru: 'Тампере' },
  { iata: 'TKU', en: 'Turku', ru: 'Турку' },
  { iata: 'GOT', en: 'Gothenburg', ru: 'Гётеборг' },
  { iata: 'BGO', en: 'Bergen', ru: 'Берген' },
  { iata: 'TRD', en: 'Trondheim', ru: 'Тронхейм' },
  { iata: 'KRS', en: 'Kristiansand', ru: 'Кристиансанн' },
  { iata: 'LJU', en: 'Ljubljana', ru: 'Любляна' },
  { iata: 'SKP', en: 'Skopje', ru: 'Скопье' },
  { iata: 'TIA', en: 'Tirana', ru: 'Тирана' },
  { iata: 'DBV', en: 'Dubrovnik', ru: 'Дубровник' },
  { iata: 'ZAD', en: 'Zadar', ru: 'Задар' },
  { iata: 'INI', en: 'Nis', ru: 'Ниш' },
  { iata: 'CLJ', en: 'Cluj-Napoca', ru: 'Клуж-Напока' },
  { iata: 'TSR', en: 'Timisoara', ru: 'Тимишоара' },
  { iata: 'HER', en: 'Heraklion', ru: 'Ираклион', aliasesEn: ['Crete'], aliasesRu: ['Крит'] },
  { iata: 'RHO', en: 'Rhodes', ru: 'Родос' },
  { iata: 'CFU', en: 'Corfu', ru: 'Корфу' },
  { iata: 'MYK', en: 'Mykonos', ru: 'Миконос' },
  { iata: 'JTR', en: 'Santorini', ru: 'Санторини' },
  { iata: 'KGS', en: 'Kos', ru: 'Кос' },
  { iata: 'ZTH', en: 'Zakynthos', ru: 'Закинф' },

  // Russia - more cities
  { iata: 'SVX', en: 'Yekaterinburg', ru: 'Екатеринбург' },
  { iata: 'OVB', en: 'Novosibirsk', ru: 'Новосибирск' },
  { iata: 'VVO', en: 'Vladivostok', ru: 'Владивосток' },
  { iata: 'KJA', en: 'Krasnoyarsk', ru: 'Красноярск' },
  { iata: 'UUS', en: 'Yuzhno-Sakhalinsk', ru: 'Южно-Сахалинск' },
  { iata: 'PEE', en: 'Petropavlovsk-Kamchatsky', ru: 'Петропавловск-Камчатский' },
  { iata: 'MQF', en: 'Magnitogorsk', ru: 'Магнитогорск' },
  { iata: 'KEJ', en: 'Kemerovo', ru: 'Кемерово' },
  { iata: 'TOF', en: 'Tolmachevo', ru: 'Толмачево' },
  { iata: 'IKT', en: 'Irkutsk', ru: 'Иркутск' },
  { iata: 'UUE', en: 'Ulan-Ude', ru: 'Улан-Удэ' },
  { iata: 'YKS', en: 'Yakutsk', ru: 'Якутск' },
  { iata: 'MRV', en: 'Mineralye Vody', ru: 'Минеральные Воды' },
  { iata: 'AER', en: 'Sochi', ru: 'Сочи' },
  { iata: 'KRR', en: 'Krasnodar', ru: 'Краснодар' },
  { iata: 'RII', en: 'Rostov-on-Don', ru: 'Ростов-на-Дону' },
  { iata: 'VOZ', en: 'Voronezh', ru: 'Воронеж' },
  { iata: 'KZN', en: 'Kazan', ru: 'Казань' },
  { iata: 'PEE', en: 'Perm', ru: 'Пермь' },
  { iata: 'IGT', en: 'Izhevsk', ru: 'Ижевск' },
  { iata: 'ARH', en: 'Arkhangelsk', ru: 'Архангельск' },
  { iata: 'MUC', en: 'Murmansk', ru: 'Мурманск' },
  { iata: 'BGI', en: 'Belgorod', ru: 'Белгород' },
  { iata: 'TYA', en: 'Tyumen', ru: 'Тюмень' },

  // USA - more cities
  { iata: 'JFK', en: 'New York', ru: 'Нью-Йорк', aliasesEn: ['New York JFK'], aliasesRu: ['Нью-Йорк JFK'] },
  { iata: 'LAX', en: 'Los Angeles', ru: 'Лос-Анджелес' },
  { iata: 'ORD', en: 'Chicago', ru: 'Чикаго' },
  { iata: 'DFW', en: 'Dallas', ru: 'Даллас' },
  { iata: 'DEN', en: 'Denver', ru: 'Денвер' },
  { iata: 'SFO', en: 'San Francisco', ru: 'Сан-Франциско' },
  { iata: 'PHX', en: 'Phoenix', ru: 'Финикс' },
  { iata: 'LAS', en: 'Las Vegas', ru: 'Лас-Вегас' },
  { iata: 'SEA', en: 'Seattle', ru: 'Сиэтл' },
  { iata: 'MIA', en: 'Miami', ru: 'Майами' },
  { iata: 'ATL', en: 'Atlanta', ru: 'Атланта' },
  { iata: 'BOS', en: 'Boston', ru: 'Бостон' },
  { iata: 'PHL', en: 'Philadelphia', ru: 'Филадельфия' },
  { iata: 'IAD', en: 'Washington DC', ru: 'Вашингтон' },
  { iata: 'DTW', en: 'Detroit', ru: 'Детройт' },
  { iata: 'MSP', en: 'Minneapolis', ru: 'Миннеаполис' },
  { iata: 'STL', en: 'St. Louis', ru: 'Сент-Луис' },
  { iata: 'IAH', en: 'Houston', ru: 'Хьюстон' },
  { iata: 'AUS', en: 'Austin', ru: 'Остин' },
  { iata: 'SAN', en: 'San Diego', ru: 'Сан-Диего' },
  { iata: 'PDX', en: 'Portland', ru: 'Портленд' },
  { iata: 'SLC', en: 'Salt Lake City', ru: 'Солт-Лейк-Сити' },
  { iata: 'ORF', en: 'Norfolk', ru: 'Норфолк' },
  { iata: 'JAX', en: 'Jacksonville', ru: 'Джексонвилл' },
  { iata: 'HNL', en: 'Honolulu', ru: 'Гонолулу' },

  // South America
  { iata: 'GIG', en: 'Rio de Janeiro', ru: 'Рио-де-Жанейро' },
  { iata: 'GRU', en: 'São Paulo', ru: 'Сан-Паулу' },
  { iata: 'FLN', en: 'Florianopolis', ru: 'Флорианополис' },
  { iata: 'BSB', en: 'Brasilia', ru: 'Бразилиа' },
  { iata: 'REC', en: 'Recife', ru: 'Ресифи' },
  { iata: 'SSA', en: 'Salvador', ru: 'Сальвадор' },
  { iata: 'BOG', en: 'Bogota', ru: 'Богота' },
  { iata: 'MDE', en: 'Medellin', ru: 'Медельин' },
  { iata: 'CTS', en: 'Cartagena', ru: 'Картахена' },
  { iata: 'MVD', en: 'Montevideo', ru: 'Монтевидео' },
  { iata: 'AEP', en: 'Buenos Aires', ru: 'Буэнос-Айрес', aliasesEn: ['Buenos Aires Aeroparque'], aliasesRu: ['Буэнос-Айрес Аэропарк'] },
  { iata: 'EZE', en: 'Buenos Aires Ministro Pistarini', ru: 'Буэнос-Айрес Интерначионал', aliasesEn: ['Buenos Aires International'], aliasesRu: ['Буэнос-Айрес'] },
  { iata: 'SCL', en: 'Santiago', ru: 'Сантьяго' },
  { iata: 'LIM', en: 'Lima', ru: 'Лима' },
  { iata: 'CUZ', en: 'Cusco', ru: 'Куско' },
  { iata: 'PEM', en: 'Puerto Montt', ru: 'Пуэрто-Монт' },
  { iata: 'CCP', en: 'Caracas', ru: 'Каракас' },
  { iata: 'CUR', en: 'Curaçao', ru: 'Кюрасао' },
  { iata: 'AUA', en: 'Aruba', ru: 'Аруба' },

  // Asia - more cities
  { iata: 'SHA', en: 'Shanghai', ru: 'Шанхай' },
  { iata: 'PVG', en: 'Shanghai Pudong', ru: 'Шанхай Пудун' },
  { iata: 'BJS', en: 'Beijing', ru: 'Пекин', aliasesEn: ['Beijing Capital'], aliasesRu: ['Пекин Капитал'] },
  { iata: 'CTU', en: 'Chengdu', ru: 'Чэнду' },
  { iata: 'XIY', en: "Xi'an", ru: 'Сиань' },
  { iata: 'HGH', en: 'Hangzhou', ru: 'Ханчжоу' },
  { iata: 'CAN', en: 'Guangzhou', ru: 'Гуанчжоу' },
  { iata: 'CKG', en: 'Chongqing', ru: 'Чунцин' },
  { iata: 'WUH', en: 'Wuhan', ru: 'Ухань' },
  { iata: 'CIH', en: 'Jinan', ru: 'Цзинань' },
  { iata: 'NKG', en: 'Nanjing', ru: 'Нанкин' },
  { iata: 'SZX', en: 'Shenzhen', ru: 'Шэньчжэнь' },
  { iata: 'WUX', en: 'Wuxi', ru: 'Учжи' },
  { iata: 'KMG', en: 'Kunming', ru: 'Куньмин' },
  { iata: 'CIX', en: 'Changsha', ru: 'Чанша' },
  { iata: 'KNM', en: 'Kunming', ru: 'Куньмин' },
  { iata: 'TYN', en: 'Taiyuan', ru: 'Тайюань' },

  // Southeast Asia
  { iata: 'BKK', en: 'Bangkok', ru: 'Бангкок' },
  { iata: 'CNX', en: 'Chiang Mai', ru: 'Чиангмай' },
  { iata: 'HAN', en: 'Hanoi', ru: 'Ханой' },
  { iata: 'SGN', en: 'Ho Chi Minh City', ru: 'Хошимин', aliasesEn: ['Saigon'], aliasesRu: ['Сайгон'] },
  { iata: 'PNH', en: 'Phnom Penh', ru: 'Пномпень' },
  { iata: 'KBV', en: 'Siem Reap', ru: 'Сиемреап' },
  { iata: 'BKI', en: 'Kota Kinabalu', ru: 'Кота-Кинабалу' },
  { iata: 'KUL', en: 'Kuala Lumpur', ru: 'Куала-Лумпур' },
  { iata: 'PEN', en: 'Penang', ru: 'Пенанг' },
  { iata: 'SGP', en: 'Singapore', ru: 'Сингапур', aliasesEn: ['Singapore Changi'], aliasesRu: ['Сингапур Чанги'] },
  { iata: 'CGK', en: 'Jakarta', ru: 'Джакарта' },
  { iata: 'DPS', en: 'Bali', ru: 'Бали', aliasesEn: ['Denpasar'], aliasesRu: ['Денпасар'] },
  { iata: 'SUB', en: 'Surabaya', ru: 'Сурабая' },
  { iata: 'MNL', en: 'Manila', ru: 'Манила' },
  { iata: 'CRK', en: 'Clark', ru: 'Кларк' },

  // Middle East & South Asia
  { iata: 'DXB', en: 'Dubai', ru: 'Дубай' },
  { iata: 'AUH', en: 'Abu Dhabi', ru: 'Абу-Даби' },
  { iata: 'RUH', en: 'Riyadh', ru: 'Эр-Рияд' },
  { iata: 'JED', en: 'Jeddah', ru: 'Джидда' },
  { iata: 'DWC', en: 'Al Maktoum', ru: 'Аль-Мактум' },
  { iata: 'RLH', en: 'Ras Al Khaimah', ru: 'Рас-эль-Хайма' },
  { iata: 'ADA', en: 'Adana', ru: 'Аданы' },
  { iata: 'KIW', en: 'Kuwait', ru: 'Кувейт' },
  { iata: 'BAH', en: 'Bahrain', ru: 'Бахрейн' },
  { iata: 'DXB', en: 'Doha', ru: 'Доха', aliasesEn: ['Hamad'], aliasesRu: ['Хамад'] },
  { iata: 'BLJ', en: 'Baku', ru: 'Баку' },
  { iata: 'GZT', en: 'Gaziantep', ru: 'Газиантеп' },
  { iata: 'GNY', en: 'Cankiri', ru: 'Джанкири' },

  // South Asia
  { iata: 'DEL', en: 'New Delhi', ru: 'Нью-Дели' },
  { iata: 'BOM', en: 'Mumbai', ru: 'Мумбаи', aliasesEn: ['Bombay'], aliasesRu: ['Бомбей'] },
  { iata: 'BLR', en: 'Bangalore', ru: 'Бангалор', aliasesEn: ['Bengaluru'], aliasesRu: ['Бенгалуру'] },
  { iata: 'COK', en: 'Kochi', ru: 'Кочин', aliasesEn: ['Cochin'], aliasesRu: ['Кохин'] },
  { iata: 'MAA', en: 'Chennai', ru: 'Ченнаи', aliasesEn: ['Madras'], aliasesRu: ['Мадрас'] },
  { iata: 'HYD', en: 'Hyderabad', ru: 'Хайдарабад' },
  { iata: 'CMB', en: 'Colombo', ru: 'Коломбо' },
  { iata: 'DAC', en: 'Dhaka', ru: 'Дакка' },
  { iata: 'KTM', en: 'Kathmandu', ru: 'Катманду' },
  { iata: 'ISB', en: 'Islamabad', ru: 'Исламабад' },
  { iata: 'LAH', en: 'Lahore', ru: 'Лахор' },
  { iata: 'KHI', en: 'Karachi', ru: 'Карачи' },

  // Oceania
  { iata: 'SYD', en: 'Sydney', ru: 'Сидней' },
  { iata: 'MEL', en: 'Melbourne', ru: 'Мельбурн' },
  { iata: 'BNE', en: 'Brisbane', ru: 'Брисбен' },
  { iata: 'PER', en: 'Perth', ru: 'Перт' },
  { iata: 'ADL', en: 'Adelaide', ru: 'Аделаида' },
  { iata: 'AKL', en: 'Auckland', ru: 'Окленд' },
  { iata: 'CHC', en: 'Christchurch', ru: 'Крайстчёрч' },
  { iata: 'WLG', en: 'Wellington', ru: 'Веллингтон' },
]
