import type { CityEntry } from './types'

export const CITY_ENTRIES: CityEntry[] = [
  { iata: 'ABZ', en: 'Aberdeen', ru: 'Абердин' },
  { iata: 'ADB', en: 'Izmir', ru: 'Измир' },
  { iata: 'ADD', en: 'Addis Ababa', ru: 'Аддис-Абеба' },
  { iata: 'AKL', en: 'Auckland', ru: 'Окленд' },
  { iata: 'ALA', en: 'Almaty', ru: 'Алматы' },
  { iata: 'ALG', en: 'Algiers', ru: 'Алжир' },
  { iata: 'AMM', en: 'Amman', ru: 'Амман' },
  { iata: 'AMS', en: 'Amsterdam', ru: 'Амстердам' },
  { iata: 'ANC', en: 'Anchorage', ru: 'Анкоридж' },
  { iata: 'ARN', en: 'Stockholm', ru: 'Стокгольм' },
  { iata: 'ASB', en: 'Ashgabat', ru: 'Ашхабад' },
  { iata: 'ATH', en: 'Athens', ru: 'Афины' },
  { iata: 'ATL', en: 'Atlanta', ru: 'Атланта' },
  { iata: 'AUH', en: 'Abu Dhabi', ru: 'Абу-Даби' },
  { iata: 'AYT', en: 'Antalya', ru: 'Анталья' },
  { iata: 'BAH', en: 'Bahrain', ru: 'Бахрейн' },
  { iata: 'BAK', en: 'Baku', ru: 'Баку', aliasesEn: ['Baku Heydar Aliyev'], aliasesRu: ['Баку Гейдар Алиев'] },
  { iata: 'BCN', en: 'Barcelona', ru: 'Барселона' },
  { iata: 'BEG', en: 'Belgrade', ru: 'Белград' },
  { iata: 'BER', en: 'Berlin', ru: 'Берлин' },
  { iata: 'BGW', en: 'Baghdad', ru: 'Багдад' },
  { iata: 'BHX', en: 'Birmingham', ru: 'Бирмингем' },
  { iata: 'BJS', en: 'Beijing', ru: 'Пекин' },
  { iata: 'BKK', en: 'Bangkok', ru: 'Бангкок' },
  { iata: 'BLQ', en: 'Bologna', ru: 'Болонья' },
  { iata: 'BNE', en: 'Brisbane', ru: 'Брисбен' },
  { iata: 'BOG', en: 'Bogota', ru: 'Богота' },
  { iata: 'BOM', en: 'Mumbai', ru: 'Мумбаи' },
  { iata: 'BOS', en: 'Boston', ru: 'Бостон' },
  { iata: 'BRU', en: 'Brussels', ru: 'Брюссель' },
  { iata: 'BSB', en: 'Brasilia', ru: 'Бразилиа' },
  { iata: 'BUD', en: 'Budapest', ru: 'Будапешт' },
  { iata: 'CAI', en: 'Cairo', ru: 'Каир' },
  { iata: 'CAN', en: 'Guangzhou', ru: 'Гуанчжоу' },
  { iata: 'CCS', en: 'Caracas', ru: 'Каракас' },
  { iata: 'CDG', en: 'Paris', ru: 'Париж', aliasesEn: ['Paris Charles de Gaulle'], aliasesRu: ['Париж Шарль-де-Голль'] },
  { iata: 'CGK', en: 'Jakarta', ru: 'Джакарта' },
  { iata: 'CMN', en: 'Casablanca', ru: 'Касабланка' },
  { iata: 'CMB', en: 'Colombo', ru: 'Коломбо' },
  { iata: 'CPH', en: 'Copenhagen', ru: 'Копенгаген' },
  { iata: 'CPT', en: 'Cape Town', ru: 'Кейптаун' },
  { iata: 'CTS', en: 'Sapporo', ru: 'Саппоро' },
  { iata: 'DAC', en: 'Dhaka', ru: 'Дакка' },
  { iata: 'DAR', en: 'Dar es Salaam', ru: 'Дар-эс-Салам' },
  { iata: 'DEL', en: 'Delhi', ru: 'Дели' },
  { iata: 'DEN', en: 'Denver', ru: 'Денвер' },
  { iata: 'DME', en: 'Moscow', ru: 'Москва', aliasesEn: ['Moscow Domodedovo'], aliasesRu: ['Москва Домодедово'] },
  { iata: 'DOH', en: 'Doha', ru: 'Доха' },
  { iata: 'DPS', en: 'Bali', ru: 'Бали', aliasesEn: ['Denpasar'], aliasesRu: ['Денпасар'] },
  { iata: 'DTW', en: 'Detroit', ru: 'Детройт' },
  { iata: 'DUB', en: 'Dublin', ru: 'Дублин' },
  { iata: 'DUS', en: 'Dusseldorf', ru: 'Дюссельдорф' },
  { iata: 'DXB', en: 'Dubai', ru: 'Дубай' },
  { iata: 'EDI', en: 'Edinburgh', ru: 'Эдинбург' },
  { iata: 'EVN', en: 'Yerevan', ru: 'Ереван' },
  { iata: 'EZE', en: 'Buenos Aires', ru: 'Буэнос-Айрес' },
  { iata: 'FCO', en: 'Rome', ru: 'Рим', aliasesEn: ['Rome Fiumicino'], aliasesRu: ['Рим Фьюмичино'] },
  { iata: 'FRA', en: 'Frankfurt', ru: 'Франкфурт' },
  { iata: 'GDN', en: 'Gdansk', ru: 'Гданьск' },
  { iata: 'GIG', en: 'Rio de Janeiro', ru: 'Рио-де-Жанейро' },
  { iata: 'GLA', en: 'Glasgow', ru: 'Глазго' },
  { iata: 'GRU', en: 'Sao Paulo', ru: 'Сан-Паулу' },
  { iata: 'GVA', en: 'Geneva', ru: 'Женева' },
  { iata: 'GYD', en: 'Baku', ru: 'Баку' },
  { iata: 'HAJ', en: 'Hanover', ru: 'Ганновер' },
  { iata: 'HAM', en: 'Hamburg', ru: 'Гамбург' },
  { iata: 'HAN', en: 'Hanoi', ru: 'Ханой' },
  { iata: 'HEL', en: 'Helsinki', ru: 'Хельсинки' },
  { iata: 'HKG', en: 'Hong Kong', ru: 'Гонконг' },
  { iata: 'HND', en: 'Tokyo Haneda', ru: 'Токио Ханэда', aliasesEn: ['Haneda'], aliasesRu: ['Ханэда'] },
  { iata: 'HNL', en: 'Honolulu', ru: 'Гонолулу' },
  { iata: 'HKT', en: 'Phuket', ru: 'Пхукет' },
  { iata: 'IAH', en: 'Houston', ru: 'Хьюстон' },
  { iata: 'ICN', en: 'Seoul', ru: 'Сеул' },
  { iata: 'IAD', en: 'Washington', ru: 'Вашингтон' },
  { iata: 'IKA', en: 'Tehran', ru: 'Тегеран' },
  { iata: 'IND', en: 'Indianapolis', ru: 'Индианаполис' },
  { iata: 'IST', en: 'Istanbul', ru: 'Стамбул', aliasesEn: ['Istanbul Airport'], aliasesRu: ['Стамбул Аэропорт'] },
  { iata: 'JED', en: 'Jeddah', ru: 'Джидда' },
  { iata: 'JFK', en: 'New York', ru: 'Нью-Йорк', aliasesEn: ['New York JFK'], aliasesRu: ['Нью-Йорк Джон Кеннеди'] },
  { iata: 'JNB', en: 'Johannesburg', ru: 'Йоханнесбург' },
  { iata: 'KBP', en: 'Kyiv', ru: 'Киев' },
  { iata: 'KHI', en: 'Karachi', ru: 'Карачи' },
  { iata: 'KIX', en: 'Osaka', ru: 'Осака' },
  { iata: 'KIV', en: 'Chisinau', ru: 'Кишинев' },
  { iata: 'KRR', en: 'Krasnodar', ru: 'Краснодар' },
  { iata: 'KUL', en: 'Kuala Lumpur', ru: 'Куала-Лумпур' },
  { iata: 'KWI', en: 'Kuwait City', ru: 'Кувейт' },
  { iata: 'KZN', en: 'Kazan', ru: 'Казань' },
  { iata: 'LAS', en: 'Las Vegas', ru: 'Лас-Вегас' },
  { iata: 'LAX', en: 'Los Angeles', ru: 'Лос-Анджелес' },
  { iata: 'LED', en: 'Saint Petersburg', ru: 'Санкт-Петербург', aliasesEn: ['St Petersburg', 'Saint-Petersburg'], aliasesRu: ['Петербург', 'Санкт Петербург'] },
  { iata: 'LGA', en: 'New York LaGuardia', ru: 'Нью-Йорк Ла-Гуардия' },
  { iata: 'LGW', en: 'London', ru: 'Лондон', aliasesEn: ['London Gatwick'], aliasesRu: ['Лондон Гатвик'] },
  { iata: 'LHR', en: 'London', ru: 'Лондон', aliasesEn: ['London Heathrow'], aliasesRu: ['Лондон Хитроу'] },
  { iata: 'LIM', en: 'Lima', ru: 'Лима' },
  { iata: 'LIS', en: 'Lisbon', ru: 'Лиссабон' },
  { iata: 'LON', en: 'London', ru: 'Лондон' },
  { iata: 'LPA', en: 'Las Palmas', ru: 'Лас-Пальмас' },
  { iata: 'LYS', en: 'Lyon', ru: 'Лион' },
  { iata: 'MAD', en: 'Madrid', ru: 'Мадрид' },
  { iata: 'MAN', en: 'Manchester', ru: 'Манчестер' },
  { iata: 'MCT', en: 'Muscat', ru: 'Маскат' },
  { iata: 'MEL', en: 'Melbourne', ru: 'Мельбурн' },
  { iata: 'MEX', en: 'Mexico City', ru: 'Мехико' },
  { iata: 'MIA', en: 'Miami', ru: 'Майами' },
  { iata: 'MLE', en: 'Male', ru: 'Мале' },
  { iata: 'MRU', en: 'Mauritius', ru: 'Маврикий' },
  { iata: 'MLA', en: 'Malta', ru: 'Мальта' },
  { iata: 'MNL', en: 'Manila', ru: 'Манила' },
  { iata: 'MOW', en: 'Moscow', ru: 'Москва' },
  { iata: 'MSP', en: 'Minneapolis', ru: 'Миннеаполис' },
  { iata: 'MUC', en: 'Munich', ru: 'Мюнхен' },
  { iata: 'NBO', en: 'Nairobi', ru: 'Найроби' },
  { iata: 'NCE', en: 'Nice', ru: 'Ницца' },
  { iata: 'NGO', en: 'Nagoya', ru: 'Нагоя' },
  { iata: 'NQZ', en: 'Astana', ru: 'Астана' },
  { iata: 'NRT', en: 'Tokyo', ru: 'Токио', aliasesEn: ['Tokyo Narita'], aliasesRu: ['Токио Нарита'] },
  { iata: 'NYC', en: 'New York', ru: 'Нью-Йорк' },
  { iata: 'NUE', en: 'Nuremberg', ru: 'Нюрнберг' },
  { iata: 'OPO', en: 'Porto', ru: 'Порту' },
  { iata: 'ORD', en: 'Chicago', ru: 'Чикаго' },
  { iata: 'OSL', en: 'Oslo', ru: 'Осло' },
  { iata: 'OTP', en: 'Bucharest', ru: 'Бухарест' },
  { iata: 'PDL', en: 'Ponta Delgada', ru: 'Понта-Делгада' },
  { iata: 'PEK', en: 'Beijing', ru: 'Пекин' },
  { iata: 'PER', en: 'Perth', ru: 'Перт' },
  { iata: 'PHL', en: 'Philadelphia', ru: 'Филадельфия' },
  { iata: 'PHX', en: 'Phoenix', ru: 'Финикс' },
  { iata: 'PMI', en: 'Palma de Mallorca', ru: 'Пальма-де-Майорка' },
  { iata: 'PRG', en: 'Prague', ru: 'Прага' },
  { iata: 'PTY', en: 'Panama City', ru: 'Панама' },
  { iata: 'PVG', en: 'Shanghai', ru: 'Шанхай' },
  { iata: 'RIX', en: 'Riga', ru: 'Рига' },
  { iata: 'RKT', en: 'Ras Al Khaimah', ru: 'Рас-эль-Хайма' },
  { iata: 'ROM', en: 'Rome', ru: 'Рим' },
  { iata: 'RUH', en: 'Riyadh', ru: 'Эр-Рияд' },
  { iata: 'SAW', en: 'Istanbul Sabiha', ru: 'Стамбул Сабиха', aliasesEn: ['Sabiha Gokcen'], aliasesRu: ['Сабиха Гёкчен'] },
  { iata: 'SEA', en: 'Seattle', ru: 'Сиэтл' },
  { iata: 'SFO', en: 'San Francisco', ru: 'Сан-Франциско' },
  { iata: 'SHA', en: 'Shanghai Hongqiao', ru: 'Шанхай Хунцяо' },
  { iata: 'SIN', en: 'Singapore', ru: 'Сингапур' },
  { iata: 'SKG', en: 'Thessaloniki', ru: 'Салоники' },
  { iata: 'SOF', en: 'Sofia', ru: 'София' },
  { iata: 'SPU', en: 'Split', ru: 'Сплит' },
  { iata: 'SVO', en: 'Moscow Sheremetyevo', ru: 'Москва Шереметьево', aliasesEn: ['Sheremetyevo'], aliasesRu: ['Шереметьево'] },
  { iata: 'SYD', en: 'Sydney', ru: 'Сидней' },
  { iata: 'TAS', en: 'Tashkent', ru: 'Ташкент' },
  { iata: 'TBS', en: 'Tbilisi', ru: 'Тбилиси' },
  { iata: 'TFN', en: 'Tenerife', ru: 'Тенерифе' },
  { iata: 'TFS', en: 'Tenerife South', ru: 'Тенерифе Южный' },
  { iata: 'TLV', en: 'Tel Aviv', ru: 'Тель-Авив' },
  { iata: 'TRN', en: 'Turin', ru: 'Турин' },
  { iata: 'TUN', en: 'Tunis', ru: 'Тунис' },
  { iata: 'UFA', en: 'Ufa', ru: 'Уфа' },
  { iata: 'VCE', en: 'Venice', ru: 'Венеция' },
  { iata: 'VIE', en: 'Vienna', ru: 'Вена' },
  { iata: 'VKO', en: 'Moscow Vnukovo', ru: 'Москва Внуково', aliasesEn: ['Vnukovo'], aliasesRu: ['Внуково'] },
  { iata: 'VNO', en: 'Vilnius', ru: 'Вильнюс' },
  { iata: 'WAW', en: 'Warsaw', ru: 'Варшава' },
  { iata: 'WRO', en: 'Wroclaw', ru: 'Вроцлав' },
  { iata: 'YEG', en: 'Edmonton', ru: 'Эдмонтон' },
  { iata: 'YUL', en: 'Montreal', ru: 'Монреаль' },
  { iata: 'YYC', en: 'Calgary', ru: 'Калгари' },
  { iata: 'YYZ', en: 'Toronto', ru: 'Торонто' },
  { iata: 'ZAG', en: 'Zagreb', ru: 'Загреб' },
  { iata: 'ZRH', en: 'Zurich', ru: 'Цюрих' },
]
